# Generated by Django 5.1.7 on 2026-05-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_userprofile_email_alter_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeInMeal',
            fields=[
            ],
            options={
                'verbose_name': 'Change In Meal',
                'verbose_name_plural': 'Change In Meal',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.userprofile',),
        ),
    ]
