# Generated by Django 5.1.7 on 2026-05-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_changeinmeal'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeInAddress',
            fields=[
            ],
            options={
                'verbose_name': 'Address Details',
                'verbose_name_plural': 'Address Details',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.userprofile',),
        ),
        migrations.AlterModelOptions(
            name='changeinmeal',
            options={'verbose_name': 'Meal Preference', 'verbose_name_plural': 'Meal Preference'},
        ),
    ]
