# Generated by Django 6.0.5 on 2026-06-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_amount_paid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_name',
            field=models.CharField(default='No Active Plan', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
