# Generated by Django 6.0.6 on 2026-06-10 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_userprofile_last_amount_paid_userprofile_plan_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('subject', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments Got',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.userprofile',),
        ),
        migrations.CreateModel(
            name='SubscriberInfo',
            fields=[
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('myapp.userprofile',),
        ),
    ]
