# Generated by Django 6.0.6 on 2026-06-10 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_enquiry_paymentinfo_subscriberinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealreview',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
