# Generated by Django 6.0.5 on 2026-06-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_userprofile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='meal_type',
            field=models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg')], default='Veg', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='menuitem',
            unique_together={('day', 'meal_type')},
        ),
    ]
